---
- name: Create service user
  user:
    name: '{{ compose_repo_service_user }}'
    groups: ['docker']

- name: 'Login into Docker registries'
  become_user: '{{ compose_repo_service_user }}'
  docker_login:
    registry_url: '{{ registry.url }}'
    username:     '{{ registry.username }}'
    password:     '{{ registry.password }}'
  with_items: '{{ compose_repo_registries }}'
  loop_control:
    loop_var: 'registry'
    label: '{{ registry.url }}'

- name: Create service directories
  file:
    path:  '{{ item }}'
    owner: '{{ compose_repo_service_user }}'
    group: '{{ compose_repo_service_group }}'
    state: 'directory'
    mode:  0755
  with_items:
    - '{{ compose_repo_service_path }}'
    - '{{ compose_repo_path }}'
